language: r
cache: packages
latex: false
#dist: trusty
sudo: required

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

before_install:
  - sudo cp fonts/ -r /usr/local/share/fonts
  - sudo fc-cache -f -v
  - chmod +x _build.sh _publish.sh

install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('tinytex')"
  - R -e "tinytex::install_tinytex()"
  #- R -e "remotes::install_github('nowosad/geostatbook')"
  #- R -e "install.packages('sp')"

r_github_packages:
  - nowosad/geostatbook

script:
  - ./_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && ./_publish.sh

notifications:
  email:
    on_success: change
    on_failure: change
